MINER_NAME="xmrig-rabid"
MINER_VER="1.0.0"
MINER_ALGO="gr-rabid"
MINER_FORK="xmrig-rabid"
MINER_EXEFILE="xmrig-rabid"
MINER_TMPFILE="/tmp/xmrig-rabid.tmp"
MINER_DESCR="RabidCoin GhostRider miner"
MINER_TITLE="xmrig-rabid"
MINER_API_PORT="44444"
